#----------------------------------------------------------------
#  makefile (NMAKE) for FBL compiler and FBL runtime
#
#  out-of-source build for debug
#----------------------------------------------------------------

CFLAGS = /DAST_NAMES /DTRACE

!INCLUDE ..\src\makefile.nmake
!INCLUDE deps.nmake
