#----------------------------------------------------------------
#  makefile (NMAKE) for FBL compiler and FBL runtime
#
#  out-of-source build for release
#----------------------------------------------------------------

!INCLUDE ..\src\makefile.nmake
!INCLUDE deps.nmake
